name: Web Installer

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio
          echo "PIP_DEFAULT_TIMEOUT=100" >> $GITHUB_ENV

      - name: Update PlatformIO platforms and packages
        run: pio update

      - name: Install PlatformIO Project Dependencies
        run: pio pkg install

      - name: Build Firmware
        run: pio run -e lolin_d32_pro

      - name: Prepare Web Installer
        run: |
          mkdir public
          # Copy web installer files if they exist, otherwise ignore
          if [ -d "web-installer" ]; then
            cp web-installer/* public/
          fi
          
          # Copy firmware binaries
          # Check if the build directory exists
          if [ -d ".pio/build/lolin_d32_pro" ]; then
            cp .pio/build/lolin_d32_pro/bootloader.bin public/ || true
            cp .pio/build/lolin_d32_pro/partitions.bin public/ || true
            cp .pio/build/lolin_d32_pro/firmware.bin public/ || true
          else
            echo "Build directory not found!"
            exit 1
          fi
          
          # boot_app0.bin is part of the framework. Use wildcard to handle versioned directories.
          find ~/.platformio/packages/framework-arduinoespressif32* -name boot_app0.bin -exec cp {} public/ \; -quit

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
